version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gafam_api
    restart: unless-stopped
    ports:
      - "5150:5150"
    volumes:
      - gafam_data:/app/data
    environment:
      - LOCO_ENV=production
      - JWT_SECRET=${JWT_SECRET:-Pq1YrzbLsBEG8GRVLxyh}
      - HOST=${HOST:-http://localhost}
      - PORT=5150

volumes:
  gafam_data:
